name: AI Code Review with xAI

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - name: Code Review
        uses: tarmojussila/xai-code-review@main
        with:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          XAI_MODEL: ${{ vars.XAI_MODEL }}
          XAI_SYSTEM_PROMPT: ${{ vars.XAI_SYSTEM_PROMPT }}
          XAI_REVIEWER_NAME: ${{ vars.XAI_REVIEWER_NAME }}
